name: skynet
description: Use Sia Skynet and SkyDB in your Dart and Flutter projects
  (Decentralized CDN and database)
version: 2.0.0
homepage: https://github.com/redsolver/skynet

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  cryptography: ^1.4.1
  http: ^0.12.2
  password_hash: ^2.0.0
  fixnum: ^0.10.11
  convert: ^2.1.1
  http_parser: ^3.1.4
  crypto: ^2.1.5
  encode_endian: ^1.0.0
  web_socket_channel: ^1.1.0
  pinenacl:
    git: https://github.com/redsolver/pinenacl-dart
  mime: ^0.9.7

dev_dependencies:
  test: ^1.15.4
