name: skynet
description: Use Sia Skynet and SkyDB in your Dart and Flutter projects.
version: 1.0.0
homepage: https://github.com/redsolver/skynet

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  cryptography: ^1.4.1
  http: ^0.12.2
  password_hash: ^2.0.0
  hex: ^0.1.2
  fixnum: ^0.10.11
  convert: ^2.1.1
  http_parser: ^3.1.4
  crypto: ^2.1.5
